//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projetki_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tunnit
    {
        public int Tunti_id { get; set; }
        public int Projekti_id { get; set; }
        public int Henkilo_id { get; set; }
        public System.DateTime Pvm { get; set; }
        public string Tunnit1 { get; set; }
    }
}
